//////////////////////////////////////////////////////////////////////////
//SockOperationId.h

#pragma once

enum{
	CMD_SERVANT_ID = 1,
	LIVE_SERVANT_ID = 2,
	SYS_MAINTANCE_SERVANT_ID = 3,

	IP_ID_CMD_BASE_ID=1000,

	//设备控制
	OP_ID_SET_CONFIG_FILE =1001,
	OP_ID_GET_CONFIG_FILE = 1002,
	OP_ID_CLEAR_SERVICE_STATISTIC = 1003, //清零业务流量统计
	OP_ID_ENABLE_MGMT_TUNNEL = 1004,
	OP_ID_DISABLE_MGMT_TUNNEL = 1005,
	OP_ID_APPLY_UPDATE_CONFIG = 1006,
	OP_ID_CHECK_UPDATE_CONFIG = 1007,

	//状态获取
	OP_ID_GET_LAN_STATE = 2000,
	OP_ID_GET_E1_STATE = 2001,
	OP_ID_GET_TUNNEL_STATE = 2002,
	OP_ID_GET_SERVICE_STATISTIC = 2003,
	OP_ID_GET_INFO = 2004,
	OP_ID_GET_VERSION = 2005,
	OP_ID_GET_MULTI_PEER_TUNNEL_STATE = 2006,

	//实时流量和状态
	OP_ID_SYS_MAINTANCE_BASE_ID = 3000,
	OP_ID_RESTOR_ORIGN = 3001,
	OP_ID_UPGRADE_SYS_PRG = 3002,
};

