//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TestControl.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TESTCONTROL_DIALOG          102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_CHANNEL_FLUX         129
#define IDD_DIALOG_CTRL_PARAM           130
#define IDD_DIALOG_CAP_CONFIG           131
#define IDB_BITMAP_LIGHT16              132
#define IDD_DIALOG_CPT_DST_FILE         136
#define IDD_IF_INFO                     137
#define IDD_OTHER_INFO                  138
#define IDD_DIALOG_ETHEREAL_DST_FILE    139
#define IDD_DIALOG_DMZ_CHANNEL_FLUX     140
#define IDD_OTHER_INFO1                 141
#define IDD_STAT_TABLE                  141
#define IDD_NAT_INFO                    142
#define IDD_NAT_INFO1                   143
#define IDD_CARD_INFO                   143
#define IDC_EDIT_INNER_TOTAL            1000
#define IDC_EDIT_FILEPATH               1000
#define IDC_EDIT_INNER_TRANS            1001
#define IDC_EDIT_FILENAME               1001
#define IDC_EDIT_INNER_IF               1002
#define IDC_EDIT_MULTIFILES             1002
#define IDC_EDIT_INNER_RATE             1003
#define IDC_EDIT_SAVE_TIME              1003
#define IDC_EDIT_OUTTER_TOTAL           1004
#define IDC_EDIT_MAX_ONEFILE_SIZE       1004
#define IDC_EDIT_OUTTER_TRANS           1005
#define IDC_EDIT_OUTTER_IF              1006
#define IDC_EDIT_OUTTER_RATE            1007
#define IDC_BUTTON_START                1008
#define IDC_BUTTON_STOP                 1009
#define IDC_EDIT_INNER_IF_BPS           1010
#define IDC_EDIT_INNER_IF_PPS           1011
#define IDC_EDIT_INNER_TOTAL_BPS        1012
#define IDC_EDIT_INNER_TOTAL_PPS        1013
#define IDC_BUTTON_CONFIG_FLT           1013
#define IDC_EDIT_INNER_TRANS_BPS        1014
#define IDC_BUTTON_CONFIG_FLT2          1014
#define IDC_BUTTON_STOP_CAP             1014
#define IDC_EDIT_INNER_TRANS_PPS        1015
#define IDC_EDIT_OUTTER_IF_BPS          1016
#define IDC_EDIT_OUTTER_IF_PPS          1017
#define IDC_BUTTON_BROWSER              1017
#define IDC_EDIT_OUTTER_TOTAL_BPS       1018
#define IDC_EDIT_OUTTER_TOTAL_PPS       1019
#define IDC_EDIT_OUTTER_TRANS_BPS       1020
#define IDC_EDIT_OUTTER_TRANS_PPS       1021
#define IDC_EDIT_RECV_BUFFER            1022
#define IDC_EDIT_SEND_BUFFER            1023
#define IDC_CHECK_FILTER                1023
#define IDC_EDIT_RECV_BUFFER2           1024
#define IDC_EDIT_SLEEP_TIME             1024
#define IDC_COMBO1                      1024
#define IDC_COMBO_FUNC_TYPE             1024
#define IDC_EDIT_PA_BUFFER              1024
#define IDC_COMBO_IF_TYPE               1024
#define IDC_EDIT_TOTAL_TOTAL            1025
#define IDC_EDIT_READ_LOOP              1025
#define IDC_EDIT_TOTAL_TRANS            1026
#define IDC_EDIT_SEND_BUFFER4           1026
#define IDC_EDIT_TIMER_PKTS             1026
#define IDC_EDIT_TOTAL_RATE             1027
#define IDC_EDIT_MAX_RECV_BUFFER        1027
#define IDC_EDIT_TOTAL_IF               1028
#define IDC_EDIT_DROP_PKTS              1028
#define IDC_EDIT_TOTAL_IF_BPS           1029
#define IDC_EDIT_DROP_PKTS2             1029
#define IDC_EDIT_DROP_PA_PKTS           1029
#define IDC_EDIT_TOTAL_IF_PPS2          1030
#define IDC_EDIT_TOTAL_IF_PPS           1030
#define IDC_EDIT_MAX_SEND_BUFFER        1030
#define IDC_EDIT_TOTAL_TOTAL_BPS        1031
#define IDC_EDIT_MAX_PA_BUFFER          1031
#define IDC_EDIT_TOTAL_TOTAL_PPS        1032
#define IDC_EDIT_TOTAL_TRANS_BPS        1033
#define IDC_EDIT_TOTAL_TRANS_PPS        1034
#define IDC_CHECK_ACL                   1035
#define IDC_CHECK_RESET_WDT_UI          1035
#define IDC_EDIT_SEND_BUFFER2           1036
#define IDC_EDIT_TIMESPEND              1036
#define IDC_LIST_CHANNEL_FLUX           1036
#define IDC_CHECK_RESET_WDT_LOOP        1036
#define IDC_BUTTON_CHANNEL_FLUX         1037
#define IDC_EDIT_TIMER                  1037
#define IDC_EDIT_TIMESPEND_SYS          1037
#define IDC_BUTTON1                     1038
#define IDC_BUTTON_REFRESH              1039
#define IDC_BUTTON_STOP_AND_EXIT        1039
#define IDC_BUTTON_CTRL_PARAM           1040
#define IDC_EDIT_TCP_TOTAL              1041
#define IDC_EDIT_TCP_CUR                1042
#define IDC_BUTTON_FILE_CONFIG          1042
#define IDC_EDIT_TCP_MAX                1043
#define IDC_EDIT_UDP_TOTAL              1044
#define IDC_EDIT_UDP_CUR                1045
#define IDC_EDIT_UDP_MAX                1046
#define IDC_BUTTON_CAP_DATA             1047
#define IDC_EDIT_TCP_TOTAL2             1047
#define IDC_BUTTON_CAP_DATA2            1048
#define IDC_BUTTON_CLEAR_PA_RUNINFO     1048
#define IDC_BUTTON_SAVE_AUTOAMP         1048
#define IDC_STATIC_POS                  1049
#define IDC_EDIT_TCP_CUR2               1049
#define IDC_RADIO_CPT                   1050
#define IDC_BUTTON_CLEAR_AUTOAMP        1050
#define IDC_EDIT_TCP_MAX2               1050
#define IDC_RADIO_ETHREAL               1051
#define IDC_EDIT_UDP_TOTAL2             1051
#define IDC_BUTTON_START_TIMER          1051
#define IDC_EDIT_TIME                   1052
#define IDC_EDIT_UDP_CUR2               1052
#define IDC_LIST1                       1053
#define IDC_LIST_LINE                   1053
#define IDC_EDIT_UDP_MAX2               1053
#define IDC_EDIT_LIVE_LOG_LEVEL         1054
#define IDC_BUTTON_STOP_TIMER           1054
#define IDC_CHECK_SYNC_ADD_STAT         1056
#define IDC_BUTTON_OUT_PUT              1057
#define IDC_CHECK_SYNC_DEL_STAT         1057
#define IDC_CHECK_FC_OUTPUT             1058
#define IDC_CHECK_WEBCONTRAVENE_OUTPUT  1059
#define IDC_CHECK_IN_DMZ_FC_OUTPUT      1060
#define IDC_CHECK_OUT_DMZ_FC_OUTPUT     1061
#define IDC_CHECK_TRACE_CODE            1062
#define IDC_LIST_PPPOE_INFO             1063
#define IDC_LIST_PPPOE_INFO2            1064
#define IDC_LIST_PPPOE_FLUX             1064
#define IDC_CHECK_LINE_1                1399
#define IDC_CHECK_LINE_2                1400
#define IDC_CHECK_LINE_3                1401
#define IDC_CHECK_LINE_4                1402
#define IDC_EDIT_BUFFER_SIZE            2010
#define IDC_BUTTON_DEFALUT_NAME         2034
#define IDC_LIST_CARD                   14092

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1064
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
